/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f3f0f2",
        "surface-container-high": "#eae7e9",
        "secondary-container": "#d0e1fb",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "surface-bright": "#fbf8fa",
        "primary-container": "#1e293b",
        "outline-variant": "#c5c6cd",
        "on-primary-fixed-variant": "#3c475a",
        "on-tertiary-fixed": "#271902",
        "surface-dim": "#dcd9db",
        "on-surface": "#1b1b1d",
        "surface-tint": "#545f73",
        "tertiary": "#1e1200",
        "on-primary-fixed": "#111c2d",
        "primary-fixed-dim": "#bcc7de",
        "on-secondary": "#ffffff",
        "primary": "#091426",
        "primary-fixed": "#d8e3fb",
        "secondary-fixed-dim": "#b7c8e1",
        "surface": "#fbf8fa",
        "surface-container-low": "#f5f3f4",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-container": "#54647a",
        "on-primary-container": "#8590a6",
        "error": "#ba1a1a",
        "secondary-fixed": "#d3e4fe",
        "tertiary-fixed": "#fadfb8",
        "background": "#fbf8fa",
        "secondary": "#505f76",
        "on-background": "#1b1b1d",
        "inverse-primary": "#bcc7de",
        "outline": "#75777d",
        "tertiary-container": "#35260c",
        "on-tertiary-container": "#a38c6a",
        "surface-container": "#f0edef",
        "on-error-container": "#93000a",
        "surface-variant": "#e4e2e3",
        "on-error": "#ffffff",
        "on-surface-variant": "#45474c",
        "on-tertiary-fixed-variant": "#564427",
        "surface-container-highest": "#e4e2e3",
        "tertiary-fixed-dim": "#ddc39d",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-surface": "#303032",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-md": "16px",
        "sidebar-width": "260px",
        "stack-sm": "8px",
        "gutter": "24px",
        "stack-lg": "24px",
        "container-max": "1440px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "caption": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "caption": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
